#!/bin/bash
#SBATCH -t 00-04:00:00
#SBATCH --mem=8000
#SBATCH -c 3

#SBATCH --mail-user=XXX.ca
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=REQUEUE
#SBATCH --mail-type=ALL

module load StdEnv/2020
module load gcc/9.3.0
module load sra-toolkit/3.0.0
module load fastqc/0.11.9
module load java/13.0.2
module load trimmomatic/0.39
module load kallisto/0.46.1

##OPEN SRA
for file in /home/XXX/SLURM/SRA/*
do
    fasterq-dump --split-files --outdir /home/XXX/SLURM/Fastq/ $file
    gzip /home/XXX/SLURM/Fastq/*
done

##CHECK QUALITY
cd /home/XXX/SLURM/Fastq
fastqc --outdir /home/XXX/SLURM/Quality *.fastq.gz

##RECONSTRUCT COMPLEMENTARY STRAND AND TRIM
cd /home/XXX/SLURM/Fastq
for file in *_1.fastq.gz
do
    base=$(basename ${file} _1.fastq.gz)
    java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar \
    PE \
    -threads 3 \
    ${file} ${base}_2.fastq.gz \
    ${base}_1.trim.fastq.gz ${base}_1unp.trim.fastq.gz \
    ${base}_2.trim.fastq.gz ${base}_2unp.trim.fastq.gz \
    SLIDINGWINDOW:4:30 MINLEN:115
done
 
mv *unp.trim.fastq.gz /home/XXX/SLURM/UnpTrimmed
mv *.trim.fastq.gz /home/XXX/SLURM/Trimmed

## GET REFERENCE GENES
cd /home/XXX/SLURM/GenomeRef/homo_sapiens
kallisto index --index="Homo_sapiens.GRCh38_index" /home/XXX/SLURM/GenomeRef/homo_sapiens/Homo_sapiens.GRCh38.cdna.all.fa.gz

## ID TRANSCRIPTS
cd /home/XXX/SLURM/Trimmed
for file in *_1.trim.fastq.gz
do
    base=$(basename ${file} _1.trim.fastq.gz)
    kallisto quant \
    --bootstrap-samples=3 \
    --threads=3 \
    --index=/home/XXX/SLURM/GenomeRef/homo_sapiens/Homo_sapiens.GRCh38_index \
    --output-dir=/home/XXX/SLURM/Quant/${base}/ \
    --genomebam \
    --gtf=/home/XXX/SLURM/GenomeRef/homo_sapiens/Homo_sapiens.GRCh38.109.chr.gtf.gz \
    --chromosomes=/home/XXX/SLURM/GenomeRef/homo_sapiens/human_chromosomes.tsv \
    ${file} ${base}_2.trim.fastq.gz
done
